---
title: "How residence time constrains diversity"
author: "Ken Locey, Jay Lennon"
date: "May 31, 2015"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE}
rm(list=ls()) 
getwd() 
setwd("~/GitHub/hydrobide") 
```

## INTRODUCTION

Here, we explore the influence of mean cell residence time, hydraulic residence time, and particle residence time on abundance, local ($\alpha$) diversity, physiology, and resource availability and diversity.

These simulations 

```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE}
#install.packages("vegan") 
require("vegan") 
```

## Load Data

```{r, results = 'hide', message = FALSE, warning = FALSE}
sim.data <- read.csv("~/GitHub/hydrobide/results/simulated_data/SimData.csv")  
```

## Univariate relationships

```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=5, fig.height=5}
par(mfrow=c(2, 2))

simulation <- sim.data$sim
height <- sim.data$Height
width <- sim.data$Width
flow.rate <- sim.data$FlowRate

h.tau <- log((height * width)/flow.rate)
m.tau <- log(sim.data$cell.tau)
t.tau <- log(sim.data$particle.tau)

plot(h.tau, m.tau, xlab="Hydraulic Residence Time", 
     ylab="Cell Residence Time", 
     col='SteelBlue')

plot(h.tau, t.tau, xlab="Hydraulic Residence Time", 
     ylab="Particle Residence Time", 
     col='darkorchid4')

plot(t.tau, m.tau, xlab="Particle Residence Time", 
     ylab="Cell Residence Time", 
     col='darkorchid4')

```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=7, fig.height=7}
par(mfrow=c(2, 2))

N <- log(sim.data$N)
S <- log(sim.data$S)

plot(t.tau, N, xlab="Particle Residence Time", 
     ylab="Total Abundance", 
     main = "N vs. Tau", col='cornsilk4')

plot(m.tau, N, xlab="Cell Residence Time", 
     ylab="Total Abundance", 
     main = "N vs. Tau", col='cornsilk4')

plot(t.tau, S, xlab="Particle Residence Time", 
     ylab="Species Richness", 
     main = "S vs. Tau", col='darkseagreen')

plot(m.tau, S, xlab="Cell Residence Time", 
     ylab="Species Richness", 
     main = "S vs. Tau", col='darkseagreen')

```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=7, fig.height=7}
par(mfrow=c(2, 2))

N <- sim.data$N
plot(m.tau, log(N), xlab="Cell Residence Time", 
     ylab="Total Abundance", 
     main = "N vs. Tau",
     col='cornsilk4')

S <- sim.data$S
plot(m.tau, log(S), xlab="Cell Residence Time", 
     ylab="Species Richness", 
     main = "S vs. Tau",
     col='darkseagreen')

e.var <- sim.data$e.var
e.simp <- sim.data$simpson.e
plot(m.tau, e.var, xlab="Cell Residence Time", 
     ylab="Species Evenness", 
     main = "Evenness vs. Tau",
     col='skyblue')

avg.ab <- N/S
plot(m.tau, log(avg.ab), xlab="Cell Residence Time", 
     ylab="Average Abundance",
     main = "N/S vs. Tau",
     col='coral')
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=7, fig.height=7}
par(mfrow=c(2, 2))

BP <- sim.data$berger.parker
plot(m.tau, BP, xlab="Cell Residence Time", 
     ylab="Berger-Parker", 
     main = "Relative Dominance vs. Tau",
     col='firebrick')

SimpD <- sim.data$inv.simp.D
plot(m.tau, SimpD, xlab="Cell Residence Time", 
     ylab="Simpsons, 1/D", 
     main = "Diversity vs. Tau",
     col='gold')

Skew <- sim.data$skew
plot(m.tau, Skew, xlab="Cell Residence Time", 
     ylab="Skewness", 
     main = "Rarity vs. Tau",
     col='limegreen')

Nmax <- sim.data$N.max
plot(m.tau, log(Nmax), xlab="Cell Residence Time", 
     ylab="Nmax",
     main = "Absolute Dominance vs. Tau",
     col='sandybrown')
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=7, fig.height=7}
par(mfrow=c(2, 2))

plot(log(N), log(S), xlab="Total abundance",
     ylab="Species Richness", 
     main = "S vs. N",
     col='indianred')

plot(log(N), log(Nmax), xlab="Total abundance", 
     ylab="Nmax", 
     main = "Nmax vs. N",
     col='darkorange')

plot(log(N), e.var, xlab="Total abundance", 
     ylab="Species Evenness", 
     main = "Evenness vs. N",
     col='lightseagreen')

plot(log(N), Skew, xlab="Total abundance", 
     ylab="Skewness",
     main = "Rarity vs. N",
     col='plum')
```



```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=7, fig.height=7}
par(mfrow=c(2, 2))

growth <- sim.data$avg.per.capita.growth
plot(m.tau, log(growth), xlab="Cell Residence Time", 
     ylab="growth", 
     main = "Per capita growth vs. Tau",
     col='dodgerblue')

maint <- sim.data$avg.per.capita.maint
plot(m.tau, SimpD, xlab="Cell Residence Time", 
     ylab="maintenance", 
     main = "Per capita maintenance vs. Tau",
     col='darkolivegreen')

immigration <- sim.data$immigration.rate
plot(m.tau, immigration, xlab="Cell Residence Time", 
     ylab="immigration", 
     main = "Immigration vs. Tau",
     col='mediumorchid')
```



```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=7, fig.height=7}
par(mfrow=c(2, 2))

res.conc <- sim.data$resource.concentration
plot(m.tau, log(res.conc), xlab="Cell Residence Time", 
     ylab="density", 
     main = "Resource density vs. Tau",
     col='peru')

res.div <- sim.data$shannons.resource.diversity
plot(m.tau, res.div, xlab="Cell Residence Time", 
     ylab="Shannon's H", 
     main = "Resource diversity vs. Tau",
     col='palegreen')

res.rich <- sim.data$resource.richness
plot(m.tau, res.rich, xlab="Cell Residence Time", 
     ylab="Number of resource types", 
     main = "Resource richness vs. Tau",
     col='slateblue')
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE}
rads <- list()
rad.list <- read.table("~/GitHub/hydrobide/results/simulated_data/RADs.csv",
            header = FALSE, sep = ",", col.names = paste0("V", seq_len(1000)),
            as.is = TRUE, skipNul = TRUE, fill = TRUE)

rad.list[is.na(rad.list)] <- 0
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE}
species <- list()
species.list <- read.table("~/GitHub/hydrobide/results/simulated_data/Species.csv",
            header = FALSE, sep = ",", col.names = paste0("V", seq_len(1000)),
            as.is = TRUE, skipNul = TRUE, fill = TRUE)

species.list[is.na(species.list)] <- -1
```



