---
title: "Exploratory analyses of simplex output"
author: "Ken Locey"
date: "October, 2015"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

## Clear and set the working directory

```{r, results = 'hide', echo=TRUE, message = FALSE, warning = FALSE}
rm(list=ls()) 
getwd() 
setwd("~/GitHub/simplex") 
```


## Import packages; install if needed

```{r, results = 'hide', echo=TRUE, message = FALSE, warning = FALSE}
#install.packages("vegan") 
require("vegan") 
library(ggplot2)
```


## Import custom modules of R functions

```{r, results = 'hide', echo=TRUE, message = FALSE, warning = FALSE}
## Loading files with plotting and diversity functions
source("~/GitHub/simplex/tools/Rbin/metrics.R")
```



## Import simulated data

```{r, results = 'hide', echo=TRUE, message = FALSE, warning = FALSE}
## Load Data
dat <- read.csv("~/GitHub/simplex/results/simulated_data/examples/SimData.csv")
ind.rtds <- get.vectors("~/GitHub/simplex/results/simulated_data/examples/IndRTD.csv")
res.rtds <- get.vectors("~/GitHub/simplex/results/simulated_data/examples/ResRTD.csv")
tracer.rtds <- get.vectors("~/GitHub/simplex/results/simulated_data/examples/TracerRTD.csv")
species.list <- get.vectors("~/GitHub/simplex/results/simulated_data/examples/Species.csv")
rads <- get.vectors("~/GitHub/simplex/results/simulated_data/examples/RADs.csv")
```


## Exploratory Analyses

### 1.) How do species richness (S) and species evenness relate to total abundance (N)?

```{r, results = 'hide', echo=TRUE, message = FALSE, warning = FALSE, fig.width=7, fig.height=4}
N <- dat$total.abundance[dat$total.abundance<=0] <- 1
S <- dat$species.richness[dat$species.richness<=0] <- 1

ggplot(dat, aes(x=dat$total.abundance, y=dat$species.richness)) +
  geom_point(colour="blue") +
  scale_x_log10() +
  scale_y_log10() +
  labs(x= "Total abundance", y="Species richness")

ggplot(dat, aes(x=dat$total.abundance, y=dat$e.var)) +
  geom_point(colour="red") +
  scale_x_log10() +
  scale_y_log10() +
  labs(x= "Total abundance", y="Species evenness")
```


### 2.) Variance partitioning


```{r, results='hide', echo=TRUE, message=F, warning=F, fig.width=7, fig.height=4}
plot.new()
dat[is.na(dat)] <- 0
dat$h.tau <- (dat$height * dat$width)/dat$flow.rate

# Physical and metacommunity variables
phys.dat <- as.matrix(subset(dat, select = c(avg.per.capita.growth,
              avg.per.capita.maint,
              avg.per.capita.N.efficiency,
              avg.per.capita.P.efficiency,
              avg.per.capita.C.efficiency)))

# Resource variables
res.dat <- as.matrix(subset(dat, 
              select = c(resource.concentration,
              shannons.resource.diversity,
              resource.richness,
              resource.particles)))

y.dat <- as.matrix(subset(dat, 
              select = c(total.abundance,
              species.richness,
              simpson.e,
              Whittakers.turnover)))

rda.phys <- rda(y.dat ~ phys.dat)
#rda.phys
rda.res <- rda(y.dat ~ res.dat)
#rda.res

# Two explanatory matrices -- Hellinger-transform Y
mod <- varpart(Y=y.dat, X=phys.dat, res.dat,  transfo="log")
mod
showvarparts(2)
plot(mod)
mtext("Variation partitioning")
#text(1.6, 0.6, "env") 
#text(-0.6, 0.6, "tau") 

# Test fraction using RDA:
phys.anova <- anova(rda.phys, step=200, perm.max=200)
phys.anova

res.anova <- anova(rda.res, step=200, perm.max=200)
res.anova
```
